README.rst
docs/how-to/use.rst
docs/index.rst
src/theme-src/yarn.lock

Some minor editing to make a somewhat stronger landing page

docs: update homepage

---

.github/workflows/lint.yml
README.rst
docs/about.rst
docs/how-to/install.rst
docs/how-to/modify.rst
docs/how-to/use.rst
noxfile.py

- Removed Gerunds in titles in the docs/* section
- Added Sphinx linkcheck session to noxfile and fixed
several broken links

docs: improvements

---

.github/workflows/lint-docs.yml
.vale/styles/Awesome/ignore/allow.txt
README.md
docs/how-to/install.md
noxfile.py

- added a logo to the PyPI badge and changed the color
- also updated a link to the github docs; it was a permanent redirect
- added the README to be run with the `lint-docs` GitHub action
- fixed Vale errors in the README

chore: update README badge

---

README.md
docs/conf.py
docs/how-to/modify.md

A few minor edits: 
- remove unused custom `:dir:` role
- make URL in README explicit
- editing in `how-to/modify`

docs: minor edits

---

.github/workflows/linkcheck.yml
.github/workflows/lint-docs.yml

updated path for GitHub actions.

fix: actions path

---

.pre-commit-config.yaml
src/theme-src/.eslintrc.js
src/theme-src/js/app.js
src/theme-src/js/controllers/clipboard-controller.js
src/theme-src/js/controllers/code-controller.js
src/theme-src/js/controllers/collapsible-controller.js
src/theme-src/js/controllers/scroll-controller.js
src/theme-src/js/controllers/search-controller.js
src/theme-src/js/controllers/sidebar-controller.js
src/theme-src/package.json
src/theme-src/stylelint.config.js
src/theme-src/yarn.lock

Style was all over the place. Now, at least it's consistent.

chore: add prettier formatting

---

README.md
pyproject.toml
tests/test_sphinxawesome_theme.py

Update the README and bump the version to prepare a new release.

chore: prepare release

---

docs/index.md
poetry.lock
src/theme-src/yarn.lock

Add a link to create a GitHub issue to the index page.

docs: update

---

docs/how-to/customize.md

Document overriding the CSS variables. Close #761.

docs: custom css properties

---

.vale/styles/Awesome/Flesch-Kincaid.yml
.vale/styles/Awesome/Smog.yml

Add Flesch-Kincaid and SMOG readability scores.

feat: readability scores

---

docs/how-to/update.md

Tried using HackMD for writing.
It's awesome, but it would be great to integrate creating a PR.

fix: typo in update

---

docs/index.md
poetry.lock

Create a new heading 'Learn more' which explains the two sections of the docs.
I also need to stop using 'overview over'.

docs: no overview over

---

docs/index.md

After fixing #797, I forgot to update the quickstart instructions on the homepage.

docs: update instructions

---

CHANGELOG.md
docs/how-to/options.md
src/sphinxawesome_theme/__init__.py
src/sphinxawesome_theme/highlighting.py

fix: highlighting inline code

---

CHANGELOG.md
docs/how-to/load.md
docs/how-to/options.md
src/sphinxawesome_theme/__init__.py
src/sphinxawesome_theme/highlighting.py

Properly render inline code. Closes #1018

fix: highlighting

---

.github/workflows/constraints.txt
.github/workflows/release.yml

Automate the GitHub release process

feat: release action

---

docs/index.md

Some minor improvements in wording.
Also including the TOC on the landing page makes it easier to navigate on smaller screens without having to show the sidebar

docs: update landing page

---

docs/_templates/page.html
docs/conf.py

Using the new `extrahead` mechanism introduced in #1267, this PR adds a script for Umami analytics.

docs: add analytics

---

docs/_static/feedback.js

- Send events when code copied
- Send events when search opened

fix: more events

---

docs/_redirects
docs/_static/feedback.css
docs/conf.py
docs/demo/includes/design-badges.rst
docs/demo/includes/design-cards.rst
docs/demo/includes/design-dropdown.rst
docs/demo/includes/design-grid.rst
docs/demo/includes/design-tabs.rst
docs/demo/sphinx-design.rst
docs/how-to/configure/includes/extension-options.rst

This PR adds a 'Demo' page for the `sphinx-design` extension.

docs: sphinx design

---

docs/how-to/install/includes/install-python-package.rst
docs/how-to/install/includes/install.sh
docs/index.rst

It's a beta release, so the installation command must use the --pre flag.

docs(install): update installation instructions

---

docs/how-to/configure/includes/docsearch.rst
poetry.lock
pyproject.toml

Using the `DocSearchHelper` for documenting the configuration options might be confusing,
so I documented the actual options.

docs(docsearch): update configuration description

---

docs/_templates/page.html

Used the wrong template block.

fix: umami analytics

---

.github/workflows/lint-docs.yml
.github/workflows/lint.yml

ci: update gh actions to use env variables
