kai687/sphinxawesome-theme

src/sphinxawesome_theme/postprocess.py

fix: non-existing figure captions do not crash HTML

---

.github/workflows/lint.yml
CHANGELOG.rst

Exclude the `./src/theme-src/` directory from triggering the `lint` action.

Improve CI

---

CHANGELOG.rst
src/sphinxawesome_theme/html_translator.py

It turns out that if you use the docutils contents directive,
the headings are differently structured (`<h1><a>Heading</a></h1>`).
This was being handled upstream just fine, I just missed this branch
in the `depart_title` method because I didn't understand what it was
for.

fix: missing implementation for headerlinks (#193)

---

CHANGELOG.rst
src/sphinxawesome_theme/footer.html
tests/roots/test-copyright/conf.py
tests/roots/test-copyright/index.rst
tests/test_copyright.py

Don't print the 'copyright' line, if the `copyright` variable is empty.

fix: prevent empty copyright (#285)

---

CHANGELOG.rst
mypy.ini
noxfile.py
poetry.lock
pyproject.toml

Mypy 0.8 changed some behavior in finding the source files.
Previously, I added the whole `tests` directory for checking
in the noxfile. This caused problems because of duplicate `conf.py`
files in the tests' 'root' directories.
Now, I pass a list of files in the `mypy.ini` section, being a bit
more explicit.

chore: mypy update

---

docs/how-to/update.md

This PR fixes broken linebreaks in the update doc. 
HTML comments must be around whole paragraphs.

fix: linebreaks in update

---

noxfile.py
requirements.txt

Allow exporting of optional dev dependencies for netlify.
This is a hack for the following use case: For building the docs, I need `myst-parser`, but the theme itself isn't dependent on this package. On the other hand, I don't want to install the full set of development dependencies, _just_ for building the docs. 
This should get addressed by Poetry 1.2.
Closes #504

chore: better dependency management

---

.github/workflows/linkcheck.yml
.github/workflows/lint.yml
noxfile.py

The link check action is now only run when there are changes to the
documentation.
I also used an `enum` to handle the supported Python versions better.

chore: separete linkcheck action

---

docs/how-to/install.md

This PR updates the installation instructions for Poetry. Poetry now uses a `install-poetry` script instead of `get-poetry`. 
Closes #508

docs: update poetry install

---

docs/conf.py
docs/index.md

The package and domain can stay the same, but _Awesome Sphinx Theme_ reads better.

fix: rename

---

pyproject.toml
src/sphinxawesome_theme/__init__.py
src/sphinxawesome_theme/jsonimpl.py

When using `sphinx-build -b json`, the docs now build correctly.
Because I pass functions and partials into the `context`, I need
to have a custom JSON encoder.

fix: JSON serializer

---

docs/about.md
docs/conf.py
docs/demo/auto.rst
docs/demo/code-blocks.rst
docs/demo/contents.rst
docs/demo/figures.rst
docs/demo/inline-code.rst
docs/demo/lists.rst
docs/demo/notes.rst
docs/demo/text.rst
docs/how-to/customize.md
docs/how-to/install.md
docs/how-to/load.md
docs/how-to/modify.md
docs/how-to/options.md
docs/how-to/update.md
docs/how-to/use.md
docs/how-to/using.md
docs/index.md

This PR adds meta descriptions to every page via frontmatter (Markdown) or the `meta` directive (reStructuredText).

docs: add meta descriptions

---

src/sphinxawesome_theme/page.html

When meta is not defined, the template `page.html` broke. Closes #662

fix: meta check

---

src/sphinxawesome_theme/html_translator.py

This PR supports a comma separated list of placeholders to be emphasised.
This is useful when declaring credentials, like an API key and an account name.
fixes #711

feat: multiple placeholders for emphasize-text

---

src/sphinxawesome_theme/postprocess.py

The same file contents were read as `utf-8`, but written with the default encoding.
On my machine, the default encoding in python programs is cp1252, which causes a UnicodeError if any generated pages include non-ANSI characters.

Fix UnicodeError when postprocessing files on Windows

---

pyproject.toml
src/theme-src/package.json
tests/test_sphinxawesome_theme.py

I messed up tagging the wrong Git commit as release and then pushing it out to PyPI.
3.2.2 is virtually the same as 3.2.1
This commit increases the version to 3.2.3, so that the git state and PyPI state will be the same. I should really automate the tagging and stuff.

chore: bump version again

---

docs/how-to/install.md
docs/how-to/load.md
docs/how-to/modify.md
docs/index.md
src/sphinxawesome_theme/highlighting.py
src/sphinxawesome_theme/html_translator.py

This PR adds a new `terminal` lexer to Sphinx, which allows me to use `terminal` as a highlighting language instead of `shell-session` or `console` which I never liked.
Until now, I had a dirty hack, where I just replaced some languages with other values when parsing. Adding a new lexer is much cleaner, as it doesn't change the default behavior. It just adds to it.

fix: allow terminal session

---

CHANGELOG.md
src/sphinxawesome_theme/__init__.py
src/sphinxawesome_theme/docsearch.py

The HTML templates expect `docsearch_config` to be present in the
context. This commit handles the inclusion/exclusion of assets
correctly, depending on whether DocSearch is used or not.

fix: bug when not using DocSearch

---

docs/how-to/install.md
docs/how-to/load.md
docs/how-to/modify.md
docs/index.md

All Markdown pages should use `html_meta` now.
I accidentally used `html_theme` on a few pages.

docs: fix meta description tag

---

.flake8

This rule flags type `Any` as errors. In some cases, I'm using docutils functions, that return `Any`, in other cases, I don't know what the type is from Sphinx, so I won't bother for now.

chore: ignore ANN401

---

CHANGELOG.md
README.md
docs/how-to/load.md
src/sphinxawesome_theme/static/docsearch_config.js_t

Just copy an empty `docsearch_config.js` file
when the theme isn't loaded as an extension.
Close #797

fix: theme works without setting extension

---

CHANGELOG.md
pyproject.toml
tests/test_sphinxawesome_theme.py

`docsearch` isn't available in the `docsearch_config.js_t` template.

fix: docsearch

---

src/sphinxawesome_theme/searchbox.html

The searchbox didn't cover the GitHub SVG in the header.

fix: z-index issue

---

CHANGELOG.md
pyproject.toml
src/sphinxawesome_theme/header.html
src/sphinxawesome_theme/layout.html
tests/test_basic.py

The Sphinx 6 update also removed `logo` in favor of `logo_url`.
This PR will make the theme work with both. Fixes #1214

fix: restore logo in header

---

CHANGELOG.md
docs/conf.py
docs/how-to/options.rst
docs/index.md
src/sphinxawesome_theme/docsearch.py
src/sphinxawesome_theme/static/docsearch_config.js_t
src/theme-src/js/docsearch_config.js_t
src/theme-src/package.json
src/theme-src/yarn.lock

This PR adds a few more options for DocSearch,
such as `placeholder`, `initial_query`, and `missing_results_url`.
As a follow up from #1262, this PR also removes quotes `"` from the caption in `options.rst`.

feat: docsearch improvements

---

docs/_templates/page.html

Just learned about the `extends "!template"` syntax for Jinja, which means I can just _extend_ the template without copying it.

fix: better override for page.html

---

pyproject.toml
src/sphinxawesome_theme/highlighting.py

Instead of copying the complete directive, this commit makes use of inheritance and adds the additional options after running the parent.

refactor(highlighting): Make AwesomeCodeBlock directive shorter
